CREATE TYPE GAME_GENRE AS ENUM ('ACTION', 'ADVENTURE', 'RPG', 'STRATEGY', 'SIMULATION', 'SPORTS', 'PUZZLE', 'HORROR', 'PLATFORMER', 'RACING', 'FIGHTING', 'SHOOTER', 'OTHER');

ALTER TABLE "games" ADD COLUMN "genre" GAME_GENRE NOT NULL DEFAULT 'OTHER';
